# Generated by Django 3.0.3 on 2020-02-19 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changeid', models.UUIDField()),
                ('status', models.IntegerField(choices=[(1, 'work-in-progres'), (2, 'applied')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.ChangeRequest')),
            ],
        ),
    ]
