# Generated by Django 3.0.3 on 2020-02-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='message',
            field=models.TextField(default='draft'),
            preserve_default=False,
        ),
    ]
